### ISSUE TITLE
我想问下10.13安装系统的时候需要修改什么参数吗？

### ISSUE THREAD

**Issue by Z-fly** [Przeblysk/MSI_X470_GAMING_PRO_AMD_2700X_NVIDIA_1070Ti_MacOS-High-Sierra#1]

**Comment by Przeblysk** [comment]
相同配置的话主板设置下就可以了，我回去上传下主板的配置图，oc的配置已经配置好了，我安装的就是10.13的系统，因为显卡是nvidia的

**Comment by Z-fly** [comment]
我看网上说安装时要设置nv_disable=1

**Comment by Z-fly** [comment]
@Przeblysk

**Comment by Przeblysk** [comment]
除非你的显示器在使用webdriver时候会黑屏不然不建议添加

**Comment by Z-fly** [comment]
> 除非你的显示器在使用webdriver时候会黑屏不然不建议添加

http://bbs.pcbeta.com/viewthread-1798018-1-1.html
http://bbs.pcbeta.com/viewthread-1823544-1-1.html

我看到有人在10.14上用10系显卡，即使无法驱动但也还能引导进系统，我现在移动硬盘里已经安装好了10.15，能用10系显卡点亮吗？

**Comment by Z-fly** [comment]
@Przeblysk 不知道这是否可行，但还是谢谢您了

**Comment by Przeblysk** [comment]
@Z-fly 10.13以上的系统，目前为止不能完美驱动n卡，基本上这是能进系统不能完美硬件驱动，如果想用高版本系统还是推荐上A卡吧，n卡还是老老实实10.13还是很稳定的，10.14部分n卡能点亮（不完美驱动），10.15我还没试过没办法帮到你。其他问题如果还有我知道的话尽管问

**Comment by Cccccxm** [comment]
现在N卡也只能10系统吗

**Comment by Z-fly** [comment]
https://heipg.cn/tutorial/drive-nvidia-graphicscard-above-mojave.html

你看下这篇
